---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: Characters
  label: Characters
  create: documents
  match: "**/*"
  templates:
  - d-d-5e
- type: heading
  label: Saga
- type: directory
  path: saga/characters
  label: Characters
  create: all
  match: "**/*"
- type: directory
  path: saga/cards
  label: Cards
  create: all
  match: "**/*"
  templates:
  - card
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
